### ISSUE TITLE
ce_command module gives error:

### ISSUE THREAD

**Issue by gemingqi** [ansible-collections/community.network#321]
##### SUMMARY
I'm trying to run "display version" command using ce_command.An error occurred during playbook execution:Unsupported parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.network.ce_command:

##### ANSIBLE VERSION
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gemingqi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gemingqi/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/gemingqi/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gemingqi/.local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.2
  libyaml = True

##### COLLECTION VERSION
V3.0.0

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
ubuntu 18.04

##### STEPS TO REPRODUCE
An error occurred during playbook execution:Unsupported parameter.

- name: command test
  hosts: host2
  connection: local
  gather_facts: no
  vars:
    cli:
     host: "120.108.67.37"
     port: "22"
     username: "huawei"
     password: "huaweiDC"

  tasks:
  - name: run display version on remote devices
    community.network.ce_command:
      commands: display version
      provider: "{{ cli }}"

##### EXPECTED RESULTS
run without error

##### ACTUAL RESULTS
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current 
version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]. This feature will be removed from ansible-core in version
 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible-playbook [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gemingqi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gemingqi/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/gemingqi/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gemingqi/.local/bin/ansible-playbook
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: command.yml *************************************************************************************************
1 plays in command.yml

PLAY [command test] ***************************************************************************************************
META: ran handlers

TASK [run display version on remote devices] **************************************************************************
task path: /home/gemingqi/Documents/command.yml:13
<120.108.67.37> using connection plugin network_cli (was local)
redirecting (type: connection) ansible.builtin.persistent to ansible.netcommon.persistent
[DEPRECATION WARNING]: connection local support for this module is deprecated use either 'network_cli' or 
'ansible.netcommon.network_cli' connection. This feature will be removed from community.network in version 4.0.0. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
<120.108.67.37> ESTABLISH LOCAL CONNECTION FOR USER: gemingqi
<120.108.67.37> EXEC /bin/sh -c 'echo ~gemingqi && sleep 0'
<120.108.67.37> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/gemingqi/.ansible/tmp `"&& mkdir "` echo /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136 `" && echo ansible-tmp-1635475908.1261353-5737-168852347136136="` echo /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136 `" ) && sleep 0'
<host2> Attempting python interpreter discovery
<120.108.67.37> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<120.108.67.37> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/gemingqi/.local/lib/python3.6/site-packages/ansible_collections/community/network/plugins/modules/ce_command.py
<120.108.67.37> PUT /home/gemingqi/.ansible/tmp/ansible-local-5730de_c5fjw/tmpzowu7m9v TO /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136/AnsiballZ_ce_command.py
<120.108.67.37> EXEC /bin/sh -c 'chmod u+x /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136/ /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136/AnsiballZ_ce_command.py && sleep 0'
<120.108.67.37> EXEC /bin/sh -c '/usr/bin/python /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136/AnsiballZ_ce_command.py && sleep 0'
<120.108.67.37> EXEC /bin/sh -c 'rm -f -r /home/gemingqi/.ansible/tmp/ansible-tmp-1635475908.1261353-5737-168852347136136/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host host2 should use /usr/bin/python3, but is using 
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using
 the discovered platform python for this host. See https://docs.ansible.com/ansible-
core/2.11/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [host2]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "display version"
            ],
            "interval": 1,
            "match": "all",
            "provider": {
                "host": "120.108.67.37",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "retries": 10,
            "transport": "cli",
            "wait_for": null
        }
    },
    "msg": "Unsupported parameters for (community.network.ce_command) module: transport. Supported parameters include: retries, commands, interval, provider, wait_for, match."
}

PLAY RECAP ************************************************************************************************************
host2                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by sirkubax** [comment]
@gemingqi  could you share your solution?
