### ISSUE TITLE
updates to team_lenovo

### ISSUE THREAD

**Issue by dericcrago** [ansible-collections/community.network#360]
Can you please make Mihai (@mihdm) and Rares (@RRNegru) maintainers for the Lenovo modules? I will be leaving Lenovo next week and these guys will take over.

_Originally posted by @istaicu in https://github.com/ansible-collections/community.network/issues/100#issuecomment-1011085785_

**Comment by dericcrago** [comment]
hi @istaicu, right now it is `team_lenovo: istaicu mihaibroc` (https://github.com/ansible-collections/community.network/blob/main/.github/BOTMETA.yml#L373)

Just so I understand, which modification are you suggesting?

```
team_lenovo: mihdm RRNegru
```

OR

```
team_lenovo: mihdm RRNegru mihaibroc
```

or feel free to raise your own PR

**Comment by dericcrago** [comment]
cc @mihaibroc

**Comment by istaicu** [comment]
> hi @istaicu, right now it is `team_lenovo: istaicu mihaibroc` (https://github.com/ansible-collections/community.network/blob/main/.github/BOTMETA.yml#L373)
> 
> Just so I understand, which modification are you suggesting?
> 
> ```
> team_lenovo: mihdm RRNegru
> ```
> 
> OR
> 
> ```
> team_lenovo: mihdm RRNegru mihaibroc
> ```
> 
> or feel free to raise your own PR

Hi @dericcrago, 
The change I suggest is the first option, because Mihai Broc left the project too. So, it should be:

team_lenovo: mihdm RRNegru

Thanks,
Ioana

**Comment by dericcrago** [comment]
Hi @istaicu - I've opened #361 for the change, please leave a comment on that PR for your approval. Thanks!
