### ISSUE TITLE
onyx_interface module does not support link speeds faster than 100G

### ISSUE THREAD

**Issue by howheels** [ansible-collections/community.network#93]
##### SUMMARY
The onyx_interface module does not support link speeds faster than 100G. The latest Onyx switches (SN3000, SN4000) support 200G or 400G link speed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
onyx_interface.py

##### ANSIBLE VERSION
```
ansible 2.9.10
  config file = /home/xxxx/ansible.cfg
  configured module search path = ['/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
DEFAULT_FORKS(/home/xxxx/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/xxxx/ansible.cfg) = ['/home/xxxx/hosts']
DEFAULT_STDOUT_CALLBACK(/home/xxxx/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/home/xxxx/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS Linux release 7.4.1708 (Core

##### STEPS TO REPRODUCE
```
- name: Configure link speed for Eth1/1
  onyx_interface:
    name: Eth1/1
    speed: 200G
```
##### EXPECTED RESULTS
Interface should be configured.

##### ACTUAL RESULTS
Task failure.

```
failed: [x.x.x.x] => changed=false 
  interface: 1/1
  msg: 'value of speed must be one of: 1G, 10G, 25G, 40G, 50G, 56G, 100G, got: 200G
```

**Comment by felixfontein** [comment]
All onyx modules have been moved to the mellanox.onyx collection (https://github.com/ansible-collections/mellanox.onyx), see #83. The next published version of community.network will no longer contain them. Can you create an issue in that repository instead? Thanks!

**Comment by howheels** [comment]
Thanks. I opened a defect there. I guess I'm going to have to learn the new way of ansible collections...

**Comment by felixfontein** [comment]
Things are starting to get settled, so it will get easier :)
